name: Deploy

on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -t jaredstemper/csc-lab:build -f ./Dockerfile .
          export IMAGE_ID_TEMP=$(sudo docker images --filter=reference=jaredstemper/csc-lab:build --format "{{.ID}}")
          echo "##[set-output name=image_id;]$IMAGE_ID_TEMP"
      - name: Login
        env:
          dockerID: ${{ secrets.dockerID }}
          dockerPassword: ${{ secrets.dockerPassword }}
        run: |
          docker login -u $dockerID -p $dockerPassword
      - name: Deploy Commit ID
        if: ${{ github.head_ref == '' && github.sha != '' && github.event_name != 'schedule' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:$GITHUB_SHA
          docker push jaredstemper/csc-lab:$GITHUB_SHA
      - name: Deploy Run Number
        if: ${{ github.head_ref == '' && github.sha != '' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:$GITHUB_RUN_NUMBER
          docker push jaredstemper/csc-lab:$GITHUB_RUN_NUMBER
      - name: Deploy Latest
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:latest
          docker push jaredstemper/csc-lab:latest
      - name: Deploy Develop
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/dev') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:latest-develop
          docker push jaredstemper/csc-lab:latest-develop
      - name: Deploy Branch
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:${GITHUB_REF##*/}
          docker push jaredstemper/csc-lab:${GITHUB_REF##*/}
      - name: Deploy Tag
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/tags/') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id jaredstemper/csc-lab:${GITHUB_REF##*/}
          docker push jaredstemper/csc-lab:${GITHUB_REF##*/}
